# Generated by Django 5.0.4 on 2025-03-19 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0003_timelineevent_about_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timelineevent',
            options={'ordering': ['year']},
        ),
    ]
