# Generated by Django 5.0.4 on 2025-03-21 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0005_skill_custom_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='proficiency',
        ),
    ]
