# Generated by Django 5.1.7 on 2025-04-14 18:58

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0007_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
